name: 'Publish Conda package to Anaconda.org (updated 2020)'
description: 'Build and Publish conda package to Anaconda'
author: 'Jens E. Pedersen, modified by Andrew Prokhorenkov and Maxime Borry'
branding:
  icon: 'package'  
  color: 'purple'
inputs: 
  subDir:
    description: 'Sub-directory with conda recipe'
    default: '.'
  AnacondaToken:
    description: 'Anaconda access Token'
runs:
  using: 'docker'
  image: 'Dockerfile'
